### PR TITLE
Added TOC, fixed ParsedownExtra link

### PR DESCRIPTION
**Pull request by S1SYPHOS**

### CODE REVIEW

**Comment by S1SYPHOS** [comment]
See #6

**Comment by tobz-nz** [comment]
The composer.json file is here, but there doesn't seem to be an entry on packagist.org so composer cannot find it.

**Comment by tovic** [comment]
https://packagist.org/packages/tovic/parsedown-extra-plugin

**Comment by tobz-nz** [comment]
👍 Strange it didn't come up in search the other day.

**Pull request merged**
